---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: "12.7.2"

platforms:
  - name: ubuntu-16.04

suites:
  - name: prabt
    data_bags_path: "test/data_bags"
    run_list:
      - recipe[cb-gwm-mysql::prabt]
    attributes:
